@extends('layouts.auth')
@section('sidebar')
    @include('layouts.guest_sidebar')
@endsection
@section('right_sidebar')
    @include('layouts.right_sidebar')
@endsection
@section('content')
    @include('posts.index')
@endsection
